name: flutter_arduino_blue
version: 1.5.0+1
publish_to: none
description: A Bluetooth Controller App Arduino and HC-05.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_bluetooth_serial: ^0.4.0
  google_fonts: 2.1.0
  scoped_model: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_native_splash: 1.3.1
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "#000000"
  image: assets/icon/icon.png

  android: true
  ios: false
  web: false
